name: 'Gin Admin Experience'
description: 'Installs and configures the Gin admin theme and supporting modules.'
type: 'Site'
install:
  # Install core dependencies.
  - config
  - help
  # Install Claro as it is a dependency of Gin, but don't import config.
  - claro
  # Install Toolbar as it is a dependency of Gin Toolbar.
  - toolbar
  - admin_toolbar
  - admin_toolbar_search
  - admin_toolbar_tools
  # Install Gin theme and base modules that extend it.
  - gin
  - gin_login
  - gin_toolbar
config:
  # Allow config import to continue if config already exists.
  strict: false
  import:
    # Import all of Admin Toolbar's modules config.
    admin_toolbar: '*'
    admin_toolbar_search: '*'
    admin_toolbar_tools: '*'
    # Import all of Gin and Gin Login's config.
    # Gin Toolbar does not have any config.
    gin:
      - gin.settings
      - block.block.gin_breadcrumbs
      - block.block.gin_content
      - block.block.gin_help
      - block.block.gin_local_actions
      - block.block.gin_messages
      - block.block.gin_page_title
      - block.block.gin_primary_local_tasks
    gin_login: '*'
  actions:
    # Set and unset Gin blocks.
    block.block.gin_admin:
      # @TODO Blocks should have setStatus config action.
      set:
        property_name: status
        value: false
    block.block.gin_branding:
      set:
        property_name: status
        value: false
    block.block.gin_local_actions:
      setRegion: content
      setWeight: -10
    block.block.gin_local_tasks:
      set:
        property_name: status
        value: false
    block.block.gin_page_title:
      setRegion: header
      setWeight: -10
    block.block.gin_primary_local_tasks:
      setRegion: header
      setWeight: -5
      # @TODO Blocks should have setSetting(s) config action.
      # We shouldn't use simpleConfigUpdate here as this is not simple config.
      simpleConfigUpdate:
        settings.secondary: true
    block.block.gin_tools:
      set:
        property_name: status
        value: false
    # Update the admin theme to Gin in Theme settings.
    node.settings:
      simpleConfigUpdate:
        use_admin_theme: true
    system.theme:
      simpleConfigUpdate:
        admin: gin
