name: 'Gin Admin Experience'
description: 'Installs and configures the Gin admin theme and supporting modules.'
type: 'Site'

install:
  # Install Claro as it is a dependency of Gin, but don't import config.
  - claro
  # Install Toolbar as it is a dependency of Gn Toolbar.
  - toolbar
  # Install Gin theme and base modules that extend it.
  - gin
  - gin_login
  - gin_toolbar

config:
  import:
    # Import all of Gin and Gin Login's config.
    # Gin Toolbar does not have any config.
    gin:
      - gin.settings
      - block.block.gin_breadcrumbs
      - block.block.gin_content
      - block.block.gin_help
      - block.block.gin_local_actions
      - block.block.gin_messages
      - block.block.gin_page_title
      - block.block.gin_primary_local_tasks
      - block.block.gin_secondary_local_tasks
    gin_login: '*'
  actions:
    # Update the admin theme to Gin in Theme settings.
    node.settings:
      simple_config_update:
        use_admin_theme: true
    system.theme:
      simple_config_update:
        admin: gin
